language: java
os: linux
jdk: openjdk8
git:
  depth: false
before_install:
  - mkdir .bin
  - curl -Lo .bin/sbt https://raw.githubusercontent.com/coursier/sbt-extras/b8bd7ec48a2540a75571d675759e452ea6587e24/sbt
  - chmod +x .bin/sbt
  - export PATH="$(pwd)/.bin:$PATH"
script: scripts/travis.sh
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - script: sbt sbt-cs-publish/scripted
    - stage: release
      script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.cache
