language: java
os: linux
jdk: openjdk8
git:
  depth: false
before_install:
  - mkdir .bin
  - curl -Lo .bin/sbt https://github.com/coursier/sbt-extras/raw/e60d803942efc3bcef877aa50b3c0917a93b4042/sbt
  - chmod +x .bin/sbt
  - export PATH="$(pwd)/.bin:$PATH"
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - script: sbt sbt-cs-publish/scripted
    - stage: release
      script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.cache
